# Generated by Django 4.1.7 on 2023-03-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, verbose_name='Род деятельности')),
            ],
            options={
                'verbose_name_plural': 'Род деятельности',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=50, verbose_name='Интересы')),
            ],
            options={
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_problem', models.CharField(max_length=50, verbose_name='Введите название проблемы')),
                ('help', models.CharField(max_length=500, verbose_name='Как решить проблему')),
            ],
            options={
                'verbose_name': 'Рекоммендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('user_sec_name', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.activity')),
                ('interests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_name', models.CharField(max_length=50, verbose_name='Имя друга')),
                ('friends_sec_name', models.CharField(max_length=50, verbose_name='Фамилия друга')),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('friends_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.activity')),
                ('friends_interests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.interests')),
            ],
            options={
                'verbose_name_plural': 'Друзья',
            },
        ),
    ]
